#!/bin/bash

# Install Docker Compose
# see https://docs.docker.com/compose/install/

set -o errexit
set -o pipefail
set -o nounset

test -z $1 && echo "Usage: $(basename $0) version" && exit

version=$1

sudo curl -L https://github.com/docker/compose/releases/download/${version}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo curl -L https://raw.githubusercontent.com/docker/compose/${version}/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

docker-compose --version
