#!/bin/bash

# install (and remove) software

set -o errexit
set -o pipefail
set -o nounset

sudo apt-get update

# update
sudo apt-get dist-upgrade -y

# great pieces of software
sudo apt-get install -y --no-install-recommends \
    curl \
    gimp \
    git \
    htop \
    httpie \
    meld \
    network-manager-openvpn \
    network-manager-openvpn-gnome \
    silversearcher-ag \
    terminator \
    tig \
    vim

# needed in git config
if [ ! -f /usr/local/bin/diff-highlight ]; then
    sudo curl https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight \
        -o /usr/local/bin/diff-highlight
    sudo chmod +x /usr/local/bin/diff-highlight
fi

# these I don't need
sudo apt-get --purge -y remove \
    evolution \
    thunderbird

sudo apt-get -y autoremove
sudo apt-get -y autoclean
