#!/bin/bash

# install (and remove) software

set -o errexit
set -o pipefail
set -o nounset

sudo apt-get update

# update
sudo apt-get dist-upgrade -y

# great pieces of software
sudo apt-get install -y --no-install-recommends \
    chromium-browser \
    curl \
    gimp \
    git \
    htop \
    httpie \
    make \
    meld \
    silversearcher-ag \
    terminator \
    tig \
    vim

# needed in git config
if [ ! -f /usr/local/bin/diff-highlight ]; then
    cp /usr/share/doc/git/contrib/diff-highlight/diff-highlight -o /usr/local/bin/diff-highlight
    sudo chmod +x /usr/local/bin/diff-highlight
fi

sudo apt-get -y autoremove
sudo apt-get -y autoclean
