#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mkdir -p /home/${USER}/.config/terminator
cp terminator/config /home/${USER}/.config/terminator/config

# copy shortcut to allow swbg to rewrite exec line
cp /usr/share/applications/terminator.desktop ~/.local/share/applications/
