#!/bin/bash

function everyplace {
    if [ -z "$3" ]
    then
        echo "Usage: $FUNCNAME SEARCH_STRING REPLACE_STRING DIRECTORY";
        return 1;
    fi

    ag -l $1 $3 | xargs sed -ri "s/$1/$2/g"
}

function vimag {
    vim $(ag -l "$@")
}

function vimgit {
    vim $(git "$@" --name-only --relative)
}

function gg {
    git branch | grep release > /dev/null && BRANCH="release" || BRANCH="master"
    git fetch origin && git rebase origin/${BRANCH} ${BRANCH}
}

function grim {
    git branch | grep release > /dev/null && BRANCH="release" || BRANCH="master"
    git rebase -i ${BRANCH}
}
