#!/bin/bash

alias myip="curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"
alias passwdgen="</dev/urandom tr -dc '12345!@#$%qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c12; echo \"\""
alias trim="sed 's/^\s*//g' | sed 's/\s*$//g'"
alias dk="docker-compose"

# open changed/staged files in vim
alias vimdi="vimgit diff --diff-filter=ACMRTUXB"
alias vimdis="vimgit diff --diff-filter=ACMRTUXB --staged"
alias vimh="vimgit diff --diff-filter=ACMRTUXB HEAD~1"

alias dockerps="docker ps --format '{{.Names}}' | sort"
