#!/bin/bash

function everysearch {
    if [ -z "$2" ]
    then
        echo "Usage: $FUNCNAME SEARCH_STRING DIRECTORY";
        return 1;
    fi

    ag -i $1 $2
}

function everyplace {
    if [ -z "$3" ]
    then
        echo "Usage: $FUNCNAME SEARCH_STRING REPLACE_STRING DIRECTORY";
        return 1;
    fi

    ag -l $1 $3 | xargs sed -ri "s/$1/$2/g"
}

function wcag {
    ag --noheading --nobreak "$@" | wc -l
}

function vimag {
    vim $(ag -l "$@")
}

function vimgit {
    vim $(git "$@" --name-only --relative)
}

function dockerip {
    if [ -z "$1" ]
    then
        echo "Usage: $FUNCNAME CONTAINER_ID_OR_NAME";
        return 1;
    fi

    docker inspect $1 | grep '"IPAddress"' | sed -E 's/.*"IPAddress": "([0-9\.]+)".*/\1/'
}

function dbash {
    if [ -z "$1" ]
    then
        echo "Usage: $FUNCNAME CONTAINER_ID_OR_NAME";
        return 1;
    fi

    docker exec -ti $1 /bin/bash
}

function phpfix {
    BRANCH="$1"
    if [ -z "$1" ]
    then
        BRANCH="master"
    fi

    git diff --name-only --diff-filter=ACMRTUXB $BRANCH | xargs -n 1 ./scripts/fixcs
}

function crowdin-cli {
    docker run --rm -it -v $(pwd):/tmp rubygem/crowdin-cli "$@"
}

function crowdin {
    docker run --rm -it -v $(pwd):/crowdin lrqdo/crowdin-cli-2 "$@"
}
